name: Dispatch

on:
  repository_dispatch:
    types:
      - Kustomization/staging-web-dev-2-global-web.flux-system

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo ${{ toJSON(github.event) }}
