name: triggered-by-label

on:
  pull_request:
    types: [ labeled ]

permissions:
  pull-requests: write

jobs:
  build:
    if: ${{ github.event.label.name == 'trigger-label' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh api /octocat
