name: triggered-by-label

on:
  pull_request:
    types: [ labeled ]

permissions:
  pull-requests: write

jobs:
  build:
    if: ${{ github.event.label.name == 'trigger-label' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: labeled_prs
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "::set-output name=count::$(gh api /repos/errm/label-workflow-foo/pulls | jq 'map(select(.labels[].name == "trigger-label")) | length')"
    - if: ${{ steps.labeled_prs.outputs.count > 1 }}
      name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          Another PR is open with the `trigger-label` label!
          Check https://github.com/errm/label-workflow-foo/pulls?q=is%3Aopen+label%3Atrigger-label+is%3Apr
          Remove the label from that PR, then relabel this PR.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - if: ${{ steps.labeled_prs.outputs.count > 1 }}
      run: exit 1
    - run: echo "do flux stuff to change the branch"

